#!/bin/bash

# Only run if files in src/ have changed (excluding those starting with _)
if git diff --cached --name-only | grep -q "^src/" && git diff --cached --name-only | grep -qvE "/_"; then
    echo "Changes detected in src/. Running bundle..."
    ./scripts/bundle.sh
    git add dist/bundle.js
fi
